### ISSUE TITLE
Unsigned integer addition does not overflow

### ISSUE THREAD

**Issue by torch2424** [AssemblyScript/assemblyscript#26]
Hello! So I think I may have found a bug with unsigned addition.

For more context, CTRL+F 0x34, on this file in my repo: https://github.com/torch2424/wasmBoy/blob/master/wasm/cpu/instructions.ts

So, I noticed if you add the constant `1` to a `u8` variable, it will not overflow from `0xFF` back down to `0x00`.

Here are some code samples:

```
// Incorrect
let badByte: u8 = 0xFF;
badByte += 1; // badByte = 0x100

//Incorrect
let anotherBadByte: u8 = 0xFF;
let badIncrementer: u8 = 1;
anotherBadByte += badIncrementer // anotherBadByte = 0x100;

// Incorrect
let badderByte: u8 = 0xFF;
let badderIncrementer: u8 = 1;
badderByte += <u8>badderIncrementer // badderByte = 0x100;

// Correct
let goodByte: u8 = 0xFF;
let goodIncrementer = 1;
goodByte = <u8>goodByte + <u8>goodIncrementer; // goodByte = 0x00
```

There are other places where I need to cast variables already declared as their appropriate types in order to do the correct over flow and things. Please let me know if you need more context.

Thanks!

**Comment by dcodeIO** [comment]
I've added a test case in the commit above that appears to succeed. Might be that the example is too basic to trigger the issue?

For reference: There is some deferred masking/sign-extending going on in the compiler, hence it's not unlikely that you found an issue there.

**Comment by torch2424** [comment]
Hmmm possibly, here is the exact code I am using:

```
  // INC (HL)
    // 1  12
    // Z 0 H -
    let registerHL: u16 = concatenateBytes(Cpu.registerH, Cpu.registerL);
    let valueAtHL: u8 = <u8>eightBitLoadFromGBMemory(registerHL);
    // Creating a varible for this to fix assemblyscript overflow bug
    // Requires explicit casting
    // https://github.com/AssemblyScript/assemblyscript/issues/26
    let incrementer: u8 = 1;
    checkAndSetEightBitHalfCarryFlag(<u8>valueAtHL, <i16>incrementer);
    valueAtHL = <u8>valueAtHL + <u8>incrementer;

    if (valueAtHL === 0) {
      setZeroFlag(1);
    } else {
      setZeroFlag(0);
    }
    setSubtractFlag(0);
    eightBitStoreIntoGBMemory(registerHL, <u8>valueAtHL);
    numberOfCycles = 12;
```

However, it did not work as:

```
// INC (HL)
    // 1  12
    // Z 0 H -
    let registerHL: u16 = concatenateBytes(Cpu.registerH, Cpu.registerL);
    let valueAtHL: u8 = eightBitLoadFromGBMemory(registerHL);
    checkAndSetEightBitHalfCarryFlag(<u8>valueAtHL, 1);
    valueAtHL += 1;
    if (valueAtHL === 0) {
      setZeroFlag(1);
    } else {
      setZeroFlag(0);
    }
    setSubtractFlag(0);
    eightBitStoreIntoGBMemory(registerHL, <u8>valueAtHL);
    numberOfCycles = 12;
```

**Comment by dcodeIO** [comment]
Hmm, haven't yet managed to reproduce. [This is the test case](https://github.com/AssemblyScript/assemblyscript/blob/master/tests/compiler/overflow.ts), maybe you have an idea?

**Comment by torch2424** [comment]
Hmmm, later tonight I'll try building an official test case, and then pass it over :) That, or maybe the issue runs deeper than just unsigned addition...

**Comment by dcodeIO** [comment]
> And if it does mean anything, there have been a handful of times where I declare a variable as u8, but the compiler will give me errors claiming that it is a u16

Hmm, one thing that comes to my mind in this regard is that binary expressions always resort to the left-hand-side type. This might result in diagnostics like this when comparing an u8 to an u16, while it's silent when comparing an u16 to an u8.

**Comment by torch2424** [comment]
Oh that would make sense!

I still owe you a test haha! I'll see if I can whip one up today, I have a break between classes. I got super invested in the emulator again so my bad I haven't made one yet. Which by the way, can play a good amount of games now (with a bunch of graphical errors haha!)

**Comment by dcodeIO** [comment]
Just tried out your emulator (running Tetris ^^) and I think I found the issue leading to invalid variable types that you reported. Essentially, when a scoped `let` declaration reused a local, the local wasn't updated with the new type, leading to random conversion warnings and possibly other strange things like not properly overflowing as well. That should be fixed now :)

Btw. with master, opcodes.ts:695, possible fix: `registerHL -= 1;`

**Comment by torch2424** [comment]
Oh wow! Thanks for checking it out! :)

So just re-install the latest assemblyscript master?

And this doesn't solve the original unsigned addition correct?

**Comment by dcodeIO** [comment]
> So just re-install the latest assemblyscript master?

Yeah, you can also point npm at it, like so, and then update occasionally: `npm install --save-dev AssemblyScript/assemblyscript`

> And this doesn't solve the original unsigned addition correct?

It might solve that as well (didn't double-check), as I see a lot of `let`s there, but not sure.

**Comment by torch2424** [comment]
Oh nice thank you! I'm going to update my wasm-playground repo, that way I have a clean slate, and do this tommorow! Totally remembered today is valentines day haha!

**Comment by torch2424** [comment]
So, got around to it tonight actually! So in my [wasm-playground]() repo, I was able to reproduce this bug!

Here is the commit from a branch I made to test bugs, with just this bug (ignore the static class thing): https://github.com/torch2424/wasm-playground/commit/6e896293ef79fc47da60ea43a54dd60c9664879f

And yes, I installed the latest assemblyscript from github 😄 

Essentially it is the following:

**In your Js file with the Wasm Instance:**
```
console.log(`unsignedIntegerOverflowBug(), 0x${instance.exports.unsignedIntegerOverflowBug().toString(16)}`);
```

**In your wasm file**
```
export function unsignedIntegerOverflowBug(): u8 {
  let badByte: u8 = 0xFF;
  badByte++;
  return badByte;
}
```

# Screenshot

![screen shot 2018-02-14 at 11 36 21 pm](https://user-images.githubusercontent.com/1448289/36245459-0024236e-11e0-11e8-8429-92f8fbb279ea.png)

**Comment by dcodeIO** [comment]
Thanks, confirming. Going to take a look :)

**Comment by dcodeIO** [comment]
The issue was that there are two cases for compiling unary increment and decrement. When context is void anyway, it skips generating a temp. local, but missed wrapping small ints, while it properly did that in the temp. local case.

Should be fixed now :)

**Comment by torch2424** [comment]
Oh rad! I'll test this, and the other cases I mentioned tonight 😄 . 

Also, This is out of the scope of this issue but, on my Wasmboy project, I noticed some weird import/export error I was getting, I don't know if it was a circular dependency or what. I'm having trouble reproducing it. Do you mind if I make another issue with that, with a branch of my repo, even though I'm not entirely sure if it's a bug on my end or yours?

And thanks again for looking through the project and stuff! :)

**Comment by dcodeIO** [comment]
Sure, the more issues, the more becomes fixed :)

Theoretically, the compiler shouldn't be affected by circular dependencies as parsing and compilation/final checking are sequential steps, but, as always, it's totally possible that I messed something up.

**Comment by torch2424** [comment]
Awesome! I'll go ahead and do that tonight once I confirm more cases on this 😄

**Comment by torch2424** [comment]
Confirmed all cases, closing this! Thanks for fixing this! 😄 

![screen shot 2018-02-15 at 8 05 21 pm](https://user-images.githubusercontent.com/1448289/36293113-b0160c0a-128b-11e8-87a6-997c3eeb15d7.png)
